ci: Introduce `make test` target, narrow CI OS matrix, update Odin release, and temporarily disable Odin check.

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -15,19 +15,20 @@ jobs:
     strategy:
       fail-fast: false
       matrix:
-        os: [ubuntu-latest, macos-latest, windows-latest, macos-15-intel]
+        os: [ubuntu-latest, macos-latest]
     runs-on: ${{ matrix.os }}
     steps:
       - uses: actions/checkout@v6
       - uses: laytan/setup-odin@v2
         with:
-          release: nightly
+          release: dev-2025-11
       - name: Report
         run: odin report
       - name: Munin test
-        run: odin test munin
+        run: make test
         timeout-minutes: 1
-      - name: Odin check
-        if: success() || failure()
-        run: odin check munin -vet --strict-style
-        timeout-minutes: 1
+      # TODO: fix odin check
+      # - name: Odin check
+      #   if: success() || failure()
+      #   run: odin check munin -vet --strict-style
+      #   timeout-minutes: 1
